import type { Piece } from './types';

const source = {
  gameVersion: 'early access 0.1, Steam build 25278619',
  reference: 'community data',
  verifiedInGame: false,
} as const;

export const pieceCatalog: readonly Piece[] = [
  {
    id: 'fob',
    name: 'Forward Operating Base',
    category: 'command',
    size: { width: 3.67, height: 13.07, depth: 3.67 },
    supplies: 30,
    hitPoints: 15_000,
    c4ToDestroy: 5,
    needsFOB: false,
    source,
  },
  {
    id: 'hesco-small',
    name: 'Hesco Block (Small)',
    category: 'hesco',
    size: { width: 1.5, height: 1.5, depth: 1.5 },
    supplies: 13,
    hitPoints: 1600,
    c4ToDestroy: 2,
    needsFOB: true,
    source,
  },
  {
    id: 'hesco-large',
    name: 'Hesco Block (Large)',
    category: 'hesco',
    size: { width: 1.5, height: 3, depth: 1.5 },
    supplies: 19,
    hitPoints: 2250,
    c4ToDestroy: 4,
    needsFOB: true,
    source,
  },
  {
    id: 'hesco-wall',
    name: 'Hesco Wall',
    category: 'hesco',
    size: { width: 1.5, height: 3.12, depth: 6 },
    supplies: 61,
    hitPoints: 4600,
    c4ToDestroy: 8,
    needsFOB: true,
    source,
  },
  {
    id: 'gate',
    name: 'Gate',
    category: 'hesco',
    size: { width: 1.5, height: 4.5, depth: 6 },
    supplies: 69,
    hitPoints: 5320,
    c4ToDestroy: 2,
    needsFOB: true,
    source,
  },
  {
    id: 'door',
    name: 'Door',
    category: 'hesco',
    size: { width: 1.5, height: 3, depth: 1.5 },
    supplies: 19,
    hitPoints: 500,
    c4ToDestroy: 1,
    needsFOB: true,
    source,
  },
  {
    id: 'bunker',
    name: 'Bunker',
    category: 'bunkers',
    size: { width: 6, height: 3, depth: 6 },
    supplies: 81,
    hitPoints: 5000,
    c4ToDestroy: 14,
    needsFOB: true,
    source,
  },
  {
    id: 'indirect-fire-shelter',
    name: 'Indirect Fire Shelter',
    category: 'bunkers',
    size: { width: 7.5, height: 4.5, depth: 7.5 },
    supplies: 81,
    hitPoints: 5000,
    c4ToDestroy: 14,
    needsFOB: true,
    source,
  },
  {
    id: 'sandbag-wall',
    name: 'Sandbag Wall',
    category: 'barriers',
    size: { width: 3, height: 1, depth: 0.34 },
    supplies: 13,
    hitPoints: 735,
    c4ToDestroy: 1,
    needsFOB: false,
    source,
  },
  {
    id: 'bremer-wall',
    name: 'Bremer Wall',
    category: 'barriers',
    size: { width: 1.5, height: 4.5, depth: 1.5 },
    supplies: 13,
    hitPoints: 6500,
    c4ToDestroy: 7,
    needsFOB: true,
    source,
  },
  {
    id: 'barbed-wire',
    name: 'Barbed Wire',
    category: 'barriers',
    size: { width: 1.5, height: 1.48, depth: 3 },
    supplies: 7,
    hitPoints: 250,
    c4ToDestroy: 1,
    needsFOB: false,
    source,
  },
  {
    id: 'hedgehog',
    name: 'Hedgehog',
    category: 'barriers',
    size: { width: 2.2, height: 2, depth: 2.2 },
    supplies: 19,
    hitPoints: 4500,
    c4ToDestroy: 3,
    needsFOB: false,
    source,
  },
  {
    id: 'recon-tent',
    name: 'Recon Tent',
    category: 'recon',
    size: { width: 2.32, height: 0.97, depth: 4.18 },
    supplies: 5,
    hitPoints: 300,
    c4ToDestroy: 1,
    needsFOB: false,
    source,
  },
  {
    id: 'recon-tower',
    name: 'Recon Tower',
    category: 'recon',
    size: { width: 6, height: 7.6, depth: 6 },
    supplies: 81,
    hitPoints: 5000,
    c4ToDestroy: 14,
    needsFOB: true,
    source,
  },
  {
    id: 'l81-mortar',
    name: 'L81 Mortar',
    category: 'defences',
    size: { width: 4.5, height: 1.64, depth: 4.5 },
    supplies: 121,
    hitPoints: 3000,
    c4ToDestroy: null,
    needsFOB: true,
    source,
  },
  {
    id: 'stingray',
    name: 'Stingray',
    category: 'defences',
    size: { width: 4.5, height: 1.64, depth: 4.5 },
    supplies: 121,
    hitPoints: 3000,
    c4ToDestroy: null,
    needsFOB: true,
    source,
  },
  {
    id: 'talon-sam',
    name: 'Talon 9K-SAM',
    category: 'defences',
    size: { width: 3, height: 1.73, depth: 3 },
    supplies: 801,
    hitPoints: 3000,
    c4ToDestroy: null,
    needsFOB: true,
    source,
  },
  {
    id: 'vanguard-ciws',
    name: 'Vanguard CIWS',
    category: 'defences',
    size: { width: 6, height: 5.01, depth: 6 },
    supplies: 1201,
    hitPoints: 5000,
    c4ToDestroy: null,
    needsFOB: true,
    source,
  },
  {
    id: 'builders-radio',
    name: "Builder's Radio",
    category: 'support',
    size: { width: 1.5, height: 1.8, depth: 3 },
    supplies: 17,
    hitPoints: 1000,
    c4ToDestroy: 1,
    needsFOB: true,
    source,
  },
  {
    id: 'loudspeaker',
    name: 'Loudspeaker',
    category: 'support',
    size: { width: 3, height: 8.77, depth: 3 },
    supplies: 81,
    hitPoints: 1000,
    c4ToDestroy: null,
    needsFOB: true,
    source,
  },
  {
    id: 'refuel-station',
    name: 'Refuel Station',
    category: 'support',
    size: { width: 3.01, height: 2.4, depth: 3 },
    supplies: 161,
    hitPoints: 1600,
    c4ToDestroy: 1,
    needsFOB: true,
    source,
  },
  {
    id: 'repair-station',
    name: 'Repair Station',
    category: 'support',
    size: { width: 3, height: 1.17, depth: 3 },
    supplies: 161,
    hitPoints: 1600,
    c4ToDestroy: 1,
    needsFOB: true,
    source,
  },
  {
    id: 'drill-rig',
    name: 'Drill Rig',
    category: 'support',
    size: { width: 4.5, height: 21.84, depth: 6 },
    supplies: 1801,
    hitPoints: 2500,
    c4ToDestroy: 2,
    needsFOB: true,
    source,
  },
];
